# Generated by Django 4.0.6 on 2022-10-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Наименование')),
                ('pharmacological_class', models.CharField(max_length=256, null=True, verbose_name='Фармакологическая группа')),
                ('form_of_release', models.CharField(max_length=64, null=True, verbose_name='Лекарственная форма')),
                ('recipe_only', models.BooleanField(null=True, verbose_name='Требуется рецепт')),
                ('active_ingredient', models.ManyToManyField(to='drugs_api.activeingredient', verbose_name='Действующее вещество')),
            ],
        ),
        migrations.CreateModel(
            name='DrugLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Ссылка')),
                ('drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs_api.drug', verbose_name='Лекарство')),
            ],
        ),
    ]
