# Generated by Django 4.0.5 on 2022-06-29 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Наименование')),
                ('active_ingredient', models.JSONField(verbose_name='Действующее вещество')),
                ('minimal_age', models.IntegerField(null=True, verbose_name='Минимальный возраст')),
                ('recipe_only', models.BooleanField(null=True, verbose_name='Требуется рецепт')),
                ('form_of_release', models.CharField(max_length=64, null=True, verbose_name='Форма выпуска')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
