# Generated by Django 4.0.6 on 2022-07-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugs_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='minimal_age',
        ),
        migrations.AddField(
            model_name='drug',
            name='med_price',
            field=models.FloatField(null=True, verbose_name='Средняя цена'),
        ),
        migrations.RemoveField(
            model_name='drug',
            name='active_ingredient',
        ),
        migrations.AlterField(
            model_name='drug',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='ActiveIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Наименование')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='active_ingredient',
            field=models.ManyToManyField(to='drugs_api.activeingredient', verbose_name='Действующее вещество'),
        ),
    ]
