# Generated by Django 4.0.5 on 2022-06-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0002_alter_drug_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='user',
        ),
    ]
