# Generated by Django 4.0.6 on 2022-10-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0002_alter_drug_form_of_release_alter_drug_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='recipe_only',
            field=models.BooleanField(default=False, null=True, verbose_name='Требуется рецепт'),
        ),
    ]
