# Generated by Django 4.0.6 on 2022-10-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0004_alter_drug_form_of_release_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='active_ingredient',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='form_of_release',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='pharmacological_class',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='recipe_only',
        ),
    ]
