# Generated by Django 4.0.5 on 2022-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0004_alter_drug_active_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='active_ingredient',
            field=models.JSONField(max_length=1024, verbose_name='Действующее вещество'),
        ),
    ]
