# Generated by Django 4.0.6 on 2022-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0005_remove_drug_active_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='active_ingredient',
            field=models.ManyToManyField(to='drugs_api.activeingredient', verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='drug',
            name='form_of_release',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Лекарственная форма'),
        ),
        migrations.AddField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, default='1', max_length=1024, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='drug',
            name='pharmacological_class',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Фармакологическая группа'),
        ),
        migrations.AddField(
            model_name='drug',
            name='recipe_only',
            field=models.BooleanField(null=True, verbose_name='Требуется рецепт'),
        ),
    ]
