# Generated by Django 4.0.6 on 2022-10-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0006_activeingredient_remove_drug_active_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='minimal_age',
        ),
        migrations.AddField(
            model_name='drug',
            name='pharmacological_class',
            field=models.CharField(max_length=256, null=True, verbose_name='Фармакологическая группа'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='active_ingredient',
            field=models.ManyToManyField(null=True, to='drugs_api.activeingredient', verbose_name='Действующее вещество'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='form_of_release',
            field=models.CharField(max_length=64, null=True, verbose_name='Лекарственная форма'),
        ),
        migrations.CreateModel(
            name='DrugLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Ссылка')),
                ('drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs_api.drug', verbose_name='Лекарство')),
            ],
        ),
    ]
