# Generated by Django 4.0.6 on 2022-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0006_drug_active_ingredient_drug_form_of_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Наименование'),
        ),
    ]
