# Generated by Django 4.0.6 on 2022-10-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0007_remove_drug_minimal_age_drug_pharmacological_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='active_ingredient',
            field=models.ManyToManyField(to='drugs_api.activeingredient', verbose_name='Действующее вещество'),
        ),
    ]
