# Generated by Django 4.0.6 on 2022-11-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0007_alter_drug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druglink',
            name='url',
            field=models.CharField(db_index=True, max_length=512, unique=True, verbose_name='Ссылка'),
        ),
    ]
