# Generated by Django 4.0.6 on 2022-11-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs_api', '0008_alter_druglink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='DrugPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.JSONField(null=True, verbose_name='Цена')),
                ('drug_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugs_api.drug', verbose_name='Лекарство')),
            ],
        ),
    ]
